services:
  app:
    container_name: alabastria-dev-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/alabastria
      - /alabastria/node_modules
      - uploads_data:/alabastria/uploads
    env_file:
      - .env.docker.development
    environment:
      - NODE_ENV=development
      - TURBOPACK_WATCH_ROOT=/alabastria
    depends_on:
      - db

  db:
    container_name: alabastria-dev-postgres
    image: postgres:18.1
    restart: always
    env_file:
      - .env.docker.development
    volumes:
      - postgres_data_dev:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  postgres_data_dev:
  uploads_data:
